package ru.ngundobin.bio.dnarepl.fwf;

import ru.ngundobin.bio.model.Genome;

import java.util.Set;

import static java.lang.System.out;

public class FrequentWordsFinderConsole {

    private FrequentWordsFinderConsole() {
        throw new AssertionError("Access denied");
    }

    public static void main(String[] args) {
        String source =
                "CGAACCAACGGCCTTAAGGTACCCAGTTATCCTCCCAGTTACGGCCTCGAACCAACGGCCTATCCTCCCAGTTACGGCCTACGGCCTCGAACCAATCCTCGAACCACCCAGTTCGAACCAACGGCCTACGGCCTCGAACCAACGGCCTCGAACCACCCAGTTTAAGGTACCCAGTTACGGCCTCCCAGTTCCCAGTTACGGCCTATCCTACGGCCTCGAACCACGAACCAACGGCCTACGGCCTTAAGGTACCCAGTTCGAACCACGAACCAATCCTTAAGGTACCCAGTTCGAACCACGAACCAATCCTCGAACCAACGGCCTTAAGGTACCCAGTTACGGCCTATCCTATCCTTAAGGTAACGGCCTTAAGGTAACGGCCTCCCAGTTCCCAGTTATCCTTAAGGTAACGGCCTCGAACCAATCCTCGAACCACGAACCAATCCTTAAGGTAACGGCCTCCCAGTTCCCAGTTCGAACCATAAGGTACCCAGTTTAAGGTAATCCTACGGCCTCGAACCACGAACCAATCCTACGGCCTCGAACCACCCAGTTATCCTTAAGGTACCCAGTTTAAGGTAACGGCCTATCCTATCCTATCCTACGGCCTCCCAGTTATCCTCGAACCACCCAGTTTAAGGTATAAGGTACCCAGTTCCCAGTTATCCTTAAGGTACGAACCACCCAGTTATCCTATCCTATCCTATCCTACGGCCTCGAACCACCCAGTTCCCAGTTCCCAGTTACGGCCTATCCTATCCTTAAGGTACCCAGTTCGAACCACCCAGTTCGAACCATAAGGTAATCCTCGAACCACGAACCAATCCTATCCTACGGCCTCGAACCAACGGCCTCGAACCAACGGCCTCGAACCATAAGGTACCCAGTTACGGCCT";
        Genome genome = new Genome(source);
        int wordLength = 11;
        int minOccurrences = 3;

        FrequentWordsFinder finder = new FrequentWordsFinder(genome);

        Set<String> found = finder.findFrequentWords(wordLength);

        for (String word : found) {
            out.print(word);
            out.print(" ");
        }
    }
}